### ISSUE TITLE
HGCategoryView 动态的调整标题的文字？

### ISSUE THREAD

**Issue by jingyu982887078** [ArchLL/HGPersonalCenterExtend#13]
HGCategoryView 如何动态的调整标题的文字？
比方说子控制1 是用户的点赞控制器，我如何在点赞数量增加的时候，优雅的修改对应的 HGCategoryView 的title的文字？谢谢

**Comment by ArchLL** [comment]
这个暂不支持，后面更新会考虑你这个需求
